import React from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { Brain, Target, Zap, TrendingUp, Users, BookOpen } from 'lucide-react'
import { BarChart3 } from "lucide-react";


const Home: React.FC = () => {
  const { currentUser } = useAuth()

  const features = [
    {
      icon: <Brain className="w-8 h-8 text-primary-500" />,
      title: "AI-Powered Learning",
      description: "Get personalized learning paths generated by advanced AI technology"
    },
    {
      icon: <Target className="w-8 h-8 text-secondary-500" />,
      title: "Adaptive Quizzes",
      description: "Dynamic quizzes that adapt to your learning pace and knowledge level"
    },
    {
      icon: <Zap className="w-8 h-8 text-accent-500" />,
      title: "Spaced Repetition",
      description: "Scientifically proven method to enhance long-term memory retention"
    },
    {
      icon: <TrendingUp className="w-8 h-8 text-success-500" />,
      title: "Progress Tracking",
      description: "Visual analytics to monitor your learning journey and achievements"
    }
  ]

  return (
    <div className="space-y-16">
      {/* Hero Section */}
      <section className="text-center py-20">
        <div className="animate-fade-in">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Master Any Subject with
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary-500 to-secondary-500">
              {" "}AI-Powered Learning
            </span>
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Transform your learning journey with personalized roadmaps, adaptive quizzes, 
            and intelligent spaced repetition. Learn smarter, not harder.
          </p>
          <div className="flex justify-center space-x-4">
            {currentUser ? (
              <Link to="/dashboard" className="btn-primary text-lg px-8 py-4">
                <BarChart3 className="w-5 h-5 mr-2" />
                Go to Dashboard
              </Link>
            ) : (
              <>
                <Link to="/register" className="btn-primary text-lg px-8 py-4">
                  Get Started Free
                </Link>
                <Link to="/login" className="btn-secondary text-lg px-8 py-4">
                  Sign In
                </Link>
              </>
            )}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Why Choose Live Learning Assistant?
          </h2>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Our platform combines cutting-edge AI with proven learning methodologies 
            to deliver a personalized education experience.
          </p>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div key={index} className="card text-center animate-slide-up" style={{ animationDelay: `${index * 0.1}s` }}>
              <div className="flex justify-center mb-4">
                {feature.icon}
              </div>
              <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
              <p className="text-gray-600">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-16 bg-gradient-to-r from-primary-50 to-secondary-50 rounded-2xl">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">How It Works</h2>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Start your learning journey in just three simple steps
          </p>
        </div>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="w-16 h-16 bg-primary-500 text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">
              1
            </div>
            <h3 className="text-lg font-semibold mb-2">Choose Your Topic</h3>
            <p className="text-gray-600">Select what you want to learn and your current skill level</p>
          </div>
          <div className="text-center">
            <div className="w-16 h-16 bg-secondary-500 text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">
              2
            </div>
            <h3 className="text-lg font-semibold mb-2">Get Your Roadmap</h3>
            <p className="text-gray-600">AI generates a personalized learning path tailored to you</p>
          </div>
          <div className="text-center">
            <div className="w-16 h-16 bg-accent-500 text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">
              3
            </div>
            <h3 className="text-lg font-semibold mb-2">Learn & Progress</h3>
            <p className="text-gray-600">Take quizzes, review concepts, and track your progress</p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      {!currentUser && (
        <section className="text-center py-16">
          <div className="card max-w-2xl mx-auto">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Ready to Transform Your Learning?
            </h2>
            <p className="text-gray-600 mb-6">
              Join thousands of learners who are already mastering new skills with our AI-powered platform.
            </p>
            <Link to="/register" className="btn-primary text-lg px-8 py-4">
              Start Learning Today
            </Link>
          </div>
        </section>
      )}
    </div>
  )
}

export default Home